version: '3.8'

services:
  springboot-demo:
    image: springboot-demo
    container_name: minha-app
    depends_on:
      - mysql
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/db_testeDocker
      SPRING_DATASOURCE_USERNAME: myuser
      SPRING_DATASOURCE_PASSWORD: mypassword


  mysql:
    image: mysql:latest
    container_name: meu-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_testeDocker
      MYSQL_USER: meuusuario
      MYSQL_PASSWORD: minhasenha
    volumes:
      - mysql-data:/var/lib/mysql



volumes:
  mysql-data: